export { default as AccountPage } from './account-page'
export { default as LoginPage } from './login-page'
export { default as RegistrationPage} from './registration-page'
export { default as NotePage } from './note-page'
export { default as NoteFormPage } from './note-form-page'
export { default as NotesPage } from './notes-page'